### ISSUE TITLE
error homebridge Honeywell-home

### ISSUE THREAD

**Issue by Harrie1966** [d0n4v4nb3ck3r/homebridge-honeywell-home#2]
@mrose17 

Best MRose 17,

I have a problem installing the plugin in Hoobs homebrige. When I search for the plugins, I find the plugin. And when I install it, I get these error messages. What goes wrong? Manual installation also gives the self-notification. It runs on a purchased raspberry version of Hoob's latest version for the raspberry raspbian buster. Can you help me with this. Thanks Harrie

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--no-update-notifier',
1 verbose cli   'install',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-honeywell-home@latest' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 8b027af72e16af70
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-honeywell-home 1333ms (from cache)
8 silly pacote tag manifest for homebridge-honeywell-home@latest fetched in 1417ms
9 timing stage:loadCurrentTree Completed in 1477ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 8ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-honeywell-home@1.2.0 checking installable status
17 silly fetchPackageMetaData error for hap-nodejs-community-types@git+https://github.com/homespun/hap-nodejs-community-types.git Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/underscore 380ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/debug 436ms (from cache)
20 silly pacote version manifest for underscore@1.8.3 fetched in 419ms
21 silly resolveWithNewModule underscore@1.8.3 checking installable status
22 silly pacote range manifest for debug@~2.6.9 fetched in 477ms
23 silly resolveWithNewModule debug@2.6.9 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/homespun-discovery 955ms (from cache)
25 silly pacote version manifest for homespun-discovery@0.3.4 fetched in 972ms
26 silly resolveWithNewModule homespun-discovery@0.3.4 checking installable status
27 timing stage:rollbackFailedOptional Completed in 3ms
28 timing stage:runTopLevelLifecycles Completed in 2557ms
29 verbose stack Error: spawn git ENOENT
29 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
29 verbose stack     at onErrorNT (internal/child_process.js:415:16)
30 verbose cwd /usr/local/lib
31 verbose Linux 4.19.58-v7+
32 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-update-notifier" "install" "--unsafe-perm" "homebridge-honeywell-home@latest"
33 verbose node v10.16.0
34 verbose npm  v6.9.0
35 error path git
36 error code ENOENT
37 error errno ENOENT
38 error syscall spawn git
39 error enoent Error while executing:
39 error enoent undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
39 error enoent
39 error enoent
39 error enoent spawn git ENOENT
40 error enoent This is related to npm not being able to find a file.
41 verbose exit [ 1, true ]

**Comment by d0n4v4nb3ck3r** [comment]
The only way I was able to get it installed was sudo -I first and then installing as instructed

**Comment by d0n4v4nb3ck3r** [comment]
Let me know if that helps?

**Comment by Harrie1966** [comment]
I was able to solve it through
sudo apt install git
to execute in the terminal. Then I could continue installing your plugin. Thank you for thinking along with my problem.

Greetings Harrie
