### ISSUE TITLE
Is D6 Pro supported?

### ISSUE THREAD

**Issue by keness521** [d0n4v4nb3ck3r/homebridge-honeywell-home#531]
I have some confusion on whether the D6 Pro is supported? I see a thread in ‘Closed Issues’ where it appears support was added, but I don’t see it in the compatible devices list or any mention anywhere other than that thread.

If I had one I’d just give it a try, but I’m thinking of buying one depending on whether it is supported or not, so I can’t.

Thanks!

**Comment by donavanbecker** [comment]
I am pretty sure it is supported but you could reach out to the user that requested support and see if is working. Than let me know and I can updated document.

**Comment by keness521** [comment]
Thanks!

Not quite sure I can figure out how to send a message to them, so I may just buy a D6 Pro anyway, since it looks promising, and I'll let you know!

If there are any issues, I'll be happy to help out if I can once I have it!
