### ISSUE TITLE
Support Request:

### ISSUE THREAD

**Issue by ajayjprakash** [d0n4v4nb3ck3r/homebridge-honeywell-home#561]
### Describe Your Problem

Linking Account is not working

### Relevant log output

```shell
I have followed the instructions to create the API keys. On next step, I clicked on Link Account, I was then able to login to Honeywell and it showed my 2 Round Thermostats. I selected all and then submitted. This then came with a page which says "Please confirm the URL below is the address of your homebridge... "

The page does not redirect when I click confirm
```

### Config for homebridge-honeywell-home

```shell
{
    "platform": "HoneywellHome",
    "name": "HoneywellHome",
    "credentials": {
        "consumerKey": "XXXXXX",
        "consumerSecret": "XXXXXXX"
    }
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/91110359/134113772-1b6f61a0-05c2-41ad-8d4f-bcdf47902d85.png)

### Device & Model

Honeywell Round Thermostat

### Node.js Version

v.14.17.5

### NPM Version

v.7.20.5

### Homebridge Version

Hoobs

### Homebridge Honeywell Home Plugin Version

10.0.1

### Homebridge Config UI X Plugin Version

10.0.1

### Operating System

Hoobs

**Comment by donavanbecker** [comment]
You need to have homebridge v1.3.4.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by ajayjprakash** [comment]
Is there anyway to update the configuration manually ?

Ajay Prakash
 Sent from a mobile device; please excuse the brevity and typo
________________________________

**Comment by shejobs** [comment]
Anyway to update the configuration manually ?

**Comment by donavanbecker** [comment]
@ajayjprakash I develop this plugin for homebridge only, Sorry.
