### ISSUE TITLE
Support Request:

### ISSUE THREAD

**Issue by mhellums** [d0n4v4nb3ck3r/homebridge-honeywell-home#569]
### Describe Your Problem

honeywell home via hoobs

### Relevant log output

```shell
I create the developer account, 
I create a new app, 
I give the app a name, and enter the Callback URL as https://homebridge-honeywell.iot.oz.nu/link-account,
I enter the consumer key and secret key into the Hoobs configuration screen,
Click Link Account, and popout tab opens,
I Login to your Honeywell Home Account, I Click Allow
I Select Devices, I Click Connect, and get please wait... screen, it doesn't head anywhere
```

### Screenshots

[Homebridge Honeywell Home.pdf](https://github.com/donavanbecker/homebridge-honeywell-home/files/7343004/Homebridge.Honeywell.Home.pdf)

### Device & Model

hoobs 4.0.109

### Node.js Version

14.18.1

### NPM Version

apache-2.0

### Homebridge Version

1.3.4

### Homebridge Honeywell Home Plugin Version

10.1.1

### Operating System

macOS

**Comment by donavanbecker** [comment]
You need to have homebridge installed.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).
