### ISSUE TITLE
Bug: Popup window to link account doesn't bring up sign in page

### ISSUE THREAD

**Issue by snopas576** [d0n4v4nb3ck3r/homebridge-honeywell-home#599]
### Describe The Bug

The "Link Account" button in Homebridge UI fails to bring up the sign in page for Honeywell, instead giving an error code 400.

### To Reproduce

Click on the Link Account Button in Homebridge UI

### Expected behavior

The sign-in page for Honeywell Home should load

### Relevant log output

```shell
This is what the browser spat out in the popup window when I clicked on the Link Account button:


code	400
message	"The redirect URL provided does not match the redirect URL registered for the app."
```

### Config for homebridge-honeywell-home

```shell
N/A
```

### Screenshots

![Screenshot (214)](https://user-images.githubusercontent.com/51276801/142794727-66e4b49b-020b-4987-ab06-cc561eae2026.png)

### Device & Model

TH6220WF2006

### Node.js Version

v16.11.1

### NPM Version

v8.0.0

### Homebridge Version

v1.3.6

### Homebridge Honeywell Home Plugin Version

v11.1.0

### Homebridge Config UI X Plugin Version

v4.41.2

### Operating System

Raspberry OS (Homebridge); Windows (the browser)

**Comment by donavanbecker** [comment]
Looks like your relink url is the same as what you are currently try to relink with.

What do you have in the relink hurl in the Honeywell developer account?

**Comment by snopas576** [comment]
The callback url in Honeywell developer is http://192.168.1.10:8581/

**Comment by donavanbecker** [comment]
It should be port `8585`

**Comment by snopas576** [comment]
That seemed to have been the issue! The copy button was being a little wonky and I believe I pasted homebridge ui's url instead.
