### ISSUE TITLE
Bug: Changelog has incorrect link for full changelog

### ISSUE THREAD

**Issue by NorthernMan54** [d0n4v4nb3ck3r/homebridge-honeywell-home#605]
### Describe The Bug

This is the current link,  https://github.com/OpenWonderLabs/homebridge-switchbot/compare/v11.0.4...v11.1.0 which is the incorrect REPO

### To Reproduce

Look at the changelog 

### Expected behavior

Link points to Honeywell home changes

### Relevant log output

```shell
No logs available
```

### Config for homebridge-honeywell-home

```shell
Not required
```

### Screenshots

![image](https://user-images.githubusercontent.com/19808920/145428304-681d4f94-90db-4743-818c-49f6b3c3c64a.png)

### Device & Model

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Homebridge Version

N/A

### Homebridge Honeywell Home Plugin Version

N/A

### Homebridge Config UI X Plugin Version

N/A

### Operating System

N/A

**Comment by donavanbecker** [comment]
This is fixed in Version 11.1.1
