### ISSUE TITLE
Bug:Cannot Change Device Settings

### ISSUE THREAD

**Issue by erictpeterson** [d0n4v4nb3ck3r/homebridge-honeywell-home#656]
### Describe The Bug

I am trying to access device settings to change PERMANENT HOLD to TEMPORARY HOLD but none of the options show up in the UI

### To Reproduce

Go to Settings > Settings > Device Settings 

### Expected behavior

I expect to see a handful of options that allow me to change aspects of the device, most specifically whether to show the fan and also to change the "hold" behavior to "temporary hold" which had been working

### Relevant log output

```shell
I am not sure what logs would be relevant here, sorry.
```

### Config for homebridge-honeywell-home

```shell
{
    "name": "HoneywellHome",
    "credentials": {
        "consumerKey": "6U5G7YRzIOyCgMwAzdge0IiIIUbyqMkQ",
        "consumerSecret": "c9EBWbFAaTtn2zBu",
        "accessToken": "AMcy7OJAZbtw3H7bfVJ9SZkaaAh4",
        "refreshToken": "Sa4k92KoAcAtJ6CvGLQfqusJNwy1mBY5"
    },
    "platform": "HoneywellHome"
}
```

### Screenshots

![Screen Shot 2022-01-22 at 1 39 05 PM](https://user-images.githubusercontent.com/77945892/150656319-5563ab41-1e47-430e-9991-273644f3a5cf.png)

I expect there to be more options under the "Honeywell Device settings"

### Device & Model

Honeywell T5 Thermostats

### Node.js Version

v16.13.2

### NPM Version

v8.1.2

### Homebridge Version

v4.42.0

### Homebridge Honeywell Home Plugin Version

v11.3.4

### Homebridge Config UI X Plugin Version

Not sure

### Operating System

macOS

**Comment by donavanbecker** [comment]
Type in your deviceID as it says. You can find this in the logs or on the Devices Tab. Once you type in the Device ID you will see settings.

**Comment by erictpeterson** [comment]
That helped a little but I still don't see most of the options I expect.

[image: Screen Shot 2022-01-22 at 3.11.48 PM.png]

**Comment by erictpeterson** [comment]
I figured it out by modifying JSON but if there is something else I am
doing wrong please let me know.  Thanks!  Awesome plug-in!

**Comment by donavanbecker** [comment]
Do you have a screenshot?

**Comment by erictpeterson** [comment]
I sent it in my first reply.

**Comment by donavanbecker** [comment]
You will need to post it on GitHub, emailing it isn't working.

**Comment by erictpeterson** [comment]
Ok

**Comment by idsnowghost** [comment]
Having this same issue with a T5 after upgrading from 10.1.x to current version. Anyone have the config JSON to share to populate the "Settings" section?
