### ISSUE TITLE
Bug: Settings tab doesn't populate when installing with T5

### ISSUE THREAD

**Issue by idsnowghost** [d0n4v4nb3ck3r/homebridge-honeywell-home#737]
### Describe The Bug

Fresh install with T5 won't populate the "Settings" tab on config.

Same issue as #656, which was closed without resolution.

### To Reproduce

1) Install and link to T5 device 
2) Click on "Settings" tab
3) Settings form doesn't populate. Nothing in config.json either for the device.

### Expected behavior

Populate "Settings tab" with form and options to set things such as Permanent/Temporary Holds

### Config for homebridge-honeywell-home

```shell
{
            "name": "HoneywellHome",
            "credentials": {
                "consumerKey": "XXXXX",
                "consumerSecret": "XXXXX",
                "accessToken": "XXXXXX",
                "refreshToken": "XXXXX"
            },
            "platform": "HoneywellHome"
        }
```

### Screenshots

Empty settings tab, with no options for configuring the device!

<img width="801" alt="Screen Shot 2022-07-24 at 1 13 25 PM" src="https://user-images.githubusercontent.com/69092157/180664288-7f5b3278-854f-41fa-bb89-f6c82c6e196d.png">

### Device & Model

T5

### Node.js Version

v16.16.0

### NPM Version

v8.11.0

### Homebridge Version

v1.5.0

### Homebridge Honeywell Home Plugin Version

v11.4.2

### Homebridge Config UI X Plugin Version

v.4.50.0

### Operating System

Raspbian

**Comment by juan2three** [comment]
I also have this issue. When clicking the “devices” tabs, it shows a loading cog but it never goes away. It might have to do from going to Resido from Honeywell

**Comment by donavanbecker** [comment]
This will be fixed in next update.
