### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by saimbhi** [d0n4v4nb3ck3r/homebridge-honeywell-home#738]
### Describe The Bug

Link account doesn't work as expected

### To Reproduce

Enter correct key and secret

### Expected behavior

Linked account

### Relevant log output

```shell
/auth& 
Doesn't work but removing /auth from server.js takes me to login and then after authorizing the window doesn't return and saves the settings.
```

### Config for homebridge-honeywell-home

```shell
config doesn't get saved from the setup screen.
```

### Device & Model

Round

### Node.js Version

latest

### NPM Version

latest

### Homebridge Version

Latest

### Homebridge Honeywell Home Plugin Version

Latest

### Operating System

Ubuntu

**Comment by donavanbecker** [comment]
Closing, will reopen when info about setup is input correctly with info and not `latest`
