### ISSUE TITLE
Support Request: Cannot find a user with these credentials

### ISSUE THREAD

**Issue by bigbadbabey** [d0n4v4nb3ck3r/homebridge-honeywell-home#779]
### Describe Your Problem

I am unable to link my Resideo Account to Home Bridge. 

### Relevant log output

```shell
[2/8/2023, 6:20:04 PM] [Homebridge UI] Running Command: /var/packages/homebridge/target/app/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-resideo 1.2.0 /volume1/homebridge/node_modules
[2/8/2023, 6:20:07 PM] [Homebridge UI] [homebridge-resideo] Incoming Request: Start Resideo Login Server
[2/8/2023, 6:21:40 PM] [Homebridge UI] [homebridge-resideo] Terminating child process...
[2/8/2023, 6:21:40 PM] [Homebridge UI] [homebridge-resideo] Child process ended
```

### Device & Model

Synology Nas

### Node.js Version

V16.16.0

### NPM Version

1.6.0

### Homebridge Version

1.6.0

### Homebridge Resideo Plugin Version

1.2.0

### Homebridge Config UI X Plugin Version

4.50.2

### Operating System

DSM 7

**Comment by donavanbecker** [comment]
Unfortunately I don't have enough info to go off of. Please provide a video or screenshots where this issue is happening.

**Comment by bigbadbabey** [comment]
<img width="1296" alt="Screenshot 2023-02-08 at 9 04 24 PM" src="https://user-images.githubusercontent.com/59376771/217715981-10c1c1e6-f37a-431d-a6d0-0d61a83c3581.png">
<img width="1296" alt="Screenshot 2023-02-08 at 9 04 15 PM" src="https://user-images.githubusercontent.com/59376771/217715987-4f25cd6f-fe6d-4c27-a3e1-a9e67431b534.png">
<img width="1296" alt="Screenshot 2023-02-08 at 9 03 46 PM" src="https://user-images.githubusercontent.com/59376771/217715990-da97d70b-7b01-4969-9726-552a21e90509.png">
<img width="831" alt="Screenshot 2023-02-08 at 8 56 35 PM" src="https://user-images.githubusercontent.com/59376771/217715994-9805e605-b59c-4959-8b77-7749e5186946.png">

**Comment by donavanbecker** [comment]
The credentials in the first image, are the credentials that you use to login to the Honeywell app, not the Honeywell developer credentials.

**Comment by bigbadbabey** [comment]
Yes, I am using my Honeywell App credentials not my developer credentials.

**Comment by donavanbecker** [comment]
That screenshot is all Honeywells interface. So if it isn't taking your email/password then not much I can do.

If you have another device that you can install Homebridge on, you could try installing on that device. If it works, you could take the refreshToken you receive from this authentication method and then input it into this instance of Homebridge.

**Comment by bigbadbabey** [comment]
I have tried this also on Home assistant and i get the same error on that long in screen. I have updated my password and even reset it to a new password. I can log into account.honeywellhome.com, would i be able to get the refreshToken from there?

**Comment by donavanbecker** [comment]
@bigbadbabey No you would. This is specific to your developer app. I really think you are using the wrong username and password.

You could try using another email. And share your thermostat to that email.


<a><img src="https://user-images.githubusercontent.com/9875439/217981169-51bcf726-91f8-4f65-a053-17e3bcb299d9.png" width="250px"></a>

**Comment by bigbadbabey** [comment]
Ok so i shared to a new account and it worked just fine? i know i was using the right username and password with the other account i could log in an out of the app no issues with it.

**Comment by donavanbecker** [comment]
Not sure, at least it is working right?

**Comment by bigbadbabey** [comment]
Yes at least it’s working!
