### ISSUE TITLE
Support Request: Hoobs install does not expose Resideo UX you show in the instructions  

### ISSUE THREAD

**Issue by Tesla-P100FX** [d0n4v4nb3ck3r/homebridge-honeywell-home#793]
### Describe Your Problem

i cannot configure the system based on the instructions for this plugin. 

### Relevant log output

```shell
i have a developer account and a Resideo account.    I can use the resideo app on my phone to control my thermostat.   i am using Hoobs 4.0 as my Homebridge platform.  in your instructions you show the UX below that never comes up on Hoobs install.   i put the consumer key and secret into the plugin settings screen, but there is on Link account button. The hoobs screen just looks like this picture that i have attached.
```

### Config for homebridge-resideo

```shell
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Resideo",
            "name": "Resideo",
            "credentials": {
                "notice": "Keep your tokens a secret!",
                "consumerKey": "sssssssss",
                "consumerSecret": "yyyyyyyyy"
            }
        }
    ]
}
```

### Screenshots

<img width="674" alt="desideo" src="https://github.com/donavanbecker/homebridge-resideo/assets/68130459/f21522b5-2889-471e-8bd1-35179972cddb">

![Hoobs Resideo](https://github.com/donavanbecker/homebridge-resideo/assets/68130459/e6bef8c7-40fc-49c1-8f5d-935e1bf632be)

### Device & Model

THM5320R

### Node.js Version

16.20.2

### NPM Version

??

### Homebridge Version

1.6.0

### Homebridge Resideo Plugin Version

1.4.1

### Operating System

RapBerryPi

**Comment by donavanbecker** [comment]
This plugin isn't developed for HOOBs.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by Tesla-P100FX** [comment]
> This plugin isn't developed for HOOBs.
> 
> 
> 
> I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

Thanks for your reply, I spent yesterday moving to homebridge .  The UX works as advertised, but it's not finding any devices, which is a separate issue.

**Comment by donavanbecker** [comment]
@Tesla-P100FX Did you see devices in the interface of linking your Honeywell account?

**Comment by Tesla-P100FX** [comment]
> @Tesla-P100FX Did you see devices in the interface of linking your Honeywell account?

No I didn't get any further than that. It didn't show on my Honeywell account.

**Comment by donavanbecker** [comment]
I would need more details (screenshots, etc.) to be able to troubleshoot.
