### ISSUE TITLE
Support Request: Callback URL is including Port, NGINX proxy in Use 

### ISSUE THREAD

**Issue by lynchpat** [d0n4v4nb3ck3r/homebridge-honeywell-home#802]
### Describe Your Problem

I am using NGINX Proxy for the URL which is http://homebridge.mydomain.com.  The Callback URL is adding :8585/auth. This port does not exist. When I add to my developer account it will not authenticate. 

### Config for homebridge-resideo

```shell
no config yet for the Resido plugin since it cannot be confirmed.
```

### Screenshots

![Screenshot 2023-11-11 at 6 32 30 PM](https://github.com/donavanbecker/homebridge-resideo/assets/17732589/b5273029-4da6-482d-92c2-d81d2280dbd0)

### Device & Model

T5

### Node.js Version

v20.9.0

### NPM Version

latest

### Homebridge Version

v1.7.0

### Homebridge Resideo Plugin Version

homebridge-resideo v1.4.2

### Homebridge Config UI X Plugin Version

homebridge-config-ui-x v4.52.2

### Operating System

Ubuntu / Docker

**Comment by donavanbecker** [comment]
Authenticate it on your local network
