### ISSUE TITLE
{"code":400, "message":"The redirect URL provided does not match the redirect URL registered for the app."}

### ISSUE THREAD

**Issue by pbrownemail** [d0n4v4nb3ck3r/homebridge-honeywell-home#809]
### Describe Your Problem

{"code":400, "message":"The redirect URL provided does not match the redirect URL registered for the app."}

### Relevant log output

```shell
no log output, issue during setup
```

### Config for homebridge-resideo

```shell
using config
```

### Device & Model

homebridge-resideo 1.4.5

### Node.js Version

1.6.1

### NPM Version

.

### Homebridge Version

18.16.1

### Homebridge Resideo Plugin Version

1.4.5

### Operating System

homebridge-reside

**Comment by donavanbecker** [comment]
I would need to be provided more information to be able to help out.

**Comment by pbrownemail** [comment]
What information do you need me to provide?

**Comment by donavanbecker** [comment]
First, Please respond and Github so we don't get all the extra stuff from email.

Second, are you using an internal ip address? what are you putting at the end? etc.

This works find for me so there isn't a bug but a setup issue.
