### ISSUE TITLE
Feature Request: Humidity Control

### ISSUE THREAD

**Issue by apitel** [d0n4v4nb3ck3r/homebridge-honeywell-home#813]
### Problem

T10 Thermostats support control of whole house humidifiers. Native Honeywell HomeKit support for humidity control is very poor. Support for humidity programming could be a nice advantage to this Homebridge solution.

### Solution

Expose humidifier control for thermostats that have it configured.

**Comment by donavanbecker** [comment]
Do you have any logs you can provide? I don't know if the API provides any info

**Comment by apitel** [comment]
Thanks for the fast response. I downloaded the Controller app and exported a JSON log of what the native Honeywell HomeKit integration is sending for a Target Relative Humidity change. Let me know if this is what log you're looking for or if there is something else I can provide:

```
[{
    "value": "55",
    "characteristicType": "00000034-0000-1000-8000-0026BB765291",
    "stringifiedValue": "55 %",
    "roomName": "Master Bedroom",
    "accessoryName": "Thermostat 1",
    "characteristicLocalizedDescription": "Target Relative Humidity",
    "serviceLocalizedDescription": "Thermostat",
    "timestamp": 727267430.935895,
    "serviceType": "0000004A-0000-1000-8000-0026BB765291",
    "id": "78EE79B3-29E2-4786-AA47-4486F3969909",
    "serviceName": "Thermostat 1",
    "serviceLabelIndex": -1
}]
```
