### ISSUE TITLE
Support Request: Can't relink account

### ISSUE THREAD

**Issue by tbaur** [d0n4v4nb3ck3r/homebridge-honeywell-home#817]
### Describe Your Problem

Can't relink account

### Relevant log output

```shell
Unclear what is going on, but after version 2.0.0 update, refresh or access token became invalid and I had to relink:

[2/5/2024, 10:46:14 AM] [Resideo] Bad Request, statusCode: 400, Action: getAccessToken
[2/5/2024, 10:46:14 AM] [Resideo] Failed to refresh token in config
[2/5/2024, 10:46:14 AM] [Resideo] Missing Access Token. Re-Link Your Resideo Account.

However, relinking fails constantly. The callback on port 8585 is running, can be loaded, but fails every single time during relink process with err_time_out -- upstream timeout?

There are misc js errors in the logs, as soon as plugin config is opened

[2/5/2024, 10:47:44 AM] [Homebridge UI] [homebridge-resideo] Incoming Request: Start Resideo Login Server
[2/5/2024, 10:47:44 AM] [Homebridge UI] [homebridge-resideo] Server is running
[2/5/2024, 10:48:10 AM] [Homebridge UI] [homebridge-resideo] (Authroize) [object Object]: {"_events":{},"_readableState":{"highWaterMark":65536,"buffer":[],"bufferIndex":0,"length":0,"pipes":[],"awaitDrainWriters":null}}, statusCode: 302
[2/5/2024, 10:48:10 AM] [Homebridge UI] [homebridge-resideo] SyntaxError: Unexpected end of JSON input
```

### Config for homebridge-resideo

```shell
None, default unconfigured, ended up trying to start over. Also tried manually inserting last known good config, no joy.
```

### Device & Model

macOS

### Node.js Version

current

### NPM Version

current

### Homebridge Version

current

### Homebridge Resideo Plugin Version

current

### Homebridge Config UI X Plugin Version

current

### Operating System

macOS

**Comment by eoddc5** [comment]
try downgrading your version to 1.4.6

this happened to me today, as well, and i moved back to that version and i was able to get everything up and running again

i updated to 2.0.0 and 2.0.1 beta and both lost my devices again, they were all showing offline. 

reinstaled 1.4.6 again, everything works again.

im not moving off the version number until its sorted

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-resideo@beta/>=2.0.1-beta.21/orange)](https://www.npmjs.com/package/homebridge-resideo)

[Click here to find out how to install Beta](https://github.com/donavanbecker/homebridge-resideo/wiki/Beta-Version)

**Comment by eoddc5** [comment]
just tried with beta.33 - looks ok so far, ill update if they disappear again

**Comment by tbaur** [comment]
Updated to beta 33 -- Callback URL is auto populated correctly on the first screen (re "Give your application a name, and enter the 'Callback URL' exactly as it is displayed below.") -- on the next screen where you enter key/secret, a new field for Callback URL exists, value is required, but the field is empty and is also not editable. Can not proceed....

**Comment by eoddc5** [comment]
also just updating to my last. with beta.33 - after about 30 minutes, the leak detectors that im linking from my resideo account fell back offline in the home app

downgrading back to 1.4.6 restored them

**Comment by tbaur** [comment]
I decided to go back to 1.4.6 as well, was able to relink and had to re-add everything, update/fix automations etc. -- will hold off on updates till things settle :)

**Comment by donavanbecker** [comment]
> I decided to go back to 1.4.6 as well, was able to relink and had to re-add everything, update/fix automations etc. -- will hold off on updates till things settle :)

you shouldn't have to remove it completely.

**Comment by eoddc5** [comment]
if he had to set everything up from scratch, then downgrading to 1.4.6 was needed

i had to blast the plugin away the other day, and then reinstall, while on any of the 2.0.x - the pop up that comes with "link account" where it offers the resideo login page just showed up blank each time, i tried to manually do it, and it wouldnt connect

going back down to 1.4.6 - the pop up portal launched properly

**Comment by ndradar** [comment]
I also am having an issue with 2.0.0 and not being able to link my account.  I get an error on the verification screen that is cannot access the server.

**Comment by JerGitHub** [comment]
Same issue as others here on v2.x. No way to re-link account - Honeywell login never appears. Downgrading to 1.4.6 restores everything.

**Comment by eoddc5** [comment]
@donavanbecker just wanted to call your attention here. i am sure its not a major issue staying on 1.4.6 - but you might want to pull 2.0.0+ for now?

**Comment by sslupsky** [comment]
Attempted to install the plugin today and ran into this problem when attempting the link step.  Browser page opens with the callback URL but the page is blank / does not load.

**Comment by tbaur** [comment]
Yeah, 2.* should really be pulled, go back to 1.4.6 and you’ll get it working.

**Comment by sslupsky** [comment]
@tbaur Thanks.  I downgraded to 1.4.6 and the link page opened correctly with using the Honeywell API URL instead of the callback URL that 2.0.x was doing.

**Comment by tbaur** [comment]
Posting to keep it alive, still needs to be solved.

2.x should also be pulled since it doesn’t work well :)

**Comment by tbaur** [comment]
@donavanbecker can you please pull 2.x? There has been no movement, so it’s not a good experience for new users that would start with the current version. And due to homebridge UI, the bad release is blocking other options — ex. you can’t move the plugin to a child bridge if there is an upgrade pending, the upgrade UI blocks / replaces that action — separate issue. 2.x is not functional. Let’s remove it please.

**Comment by bwp91** [comment]
> And due to homebridge UI, the bad release is blocking other options — ex. you can’t move the plugin to a child bridge if there is an upgrade pending, the upgrade UI blocks / replaces that action — separate issue

Looking at this for the UI 👀

**Comment by bwp91** [comment]
![Screenshot 2024-04-20 at 05 18 37](https://github.com/donavanbecker/homebridge-resideo/assets/43026681/69a813e2-9acc-491b-ba58-2e3b3477a4a2)

@tbaur UI issue is fixed in the UI beta version, and will be part of the next release.

Now I shall leave this thread, not that I was really invited in the first place 😆

**Comment by tbaur** [comment]
Nice, that’ll help various problems :)

**Comment by donavanbecker** [comment]
Can you try v2.0.1?

**Comment by tbaur** [comment]
Updated, nothing broke. Moved it into a child bridge, nothing broke. 

Progress.

Haven’t tried unlink/relinking flow, though.

**Comment by tbaur** [comment]
Spoke too soon, I guess.

[4/27/2024, 7:11:59 PM] [Resideo] Leak Sensor: Mechanical failed to refreshStatus,
[… same for all the others ]

And yep, relinking does not work. Same symptoms and problem.

Went back to 1.4.6 

You should be able to test and see the same, before releasing. I had presumed you can repo?

**Comment by cjvogl** [comment]
+1 I also have the same problems as discussed above: cannot relink account after upgrading v2.0.0 or v.2.0.1.  Second time rolling back to v.1.4.6 and having to reset all related automations.

**Comment by tbaur** [comment]
@donavanbecker again, can you please pull 2.0.0 / 2.0.1 from the release train, push to beta if you want until you have time to focus on the proper resolve, these are not viable releases for users to start from. 

This issue has been open since feb. 

I just had to walk a friend thought getting the plugin to work, as the current “release” (2.0.1), and the prior “release” (2.0.0) are totally broken. New users have no hope man. Flip the bit, at least...

**Comment by donavanbecker** [comment]
I can't pull those version but I just set v1.4.6 as `latest` for now. Also set 2.0.1 to` beta` tag, which then makes Homebridge not ask you to upgrade.

**Comment by tbaur** [comment]
Looks like 2.0.1 is now marked beta, so thats a good bit flipped and yes 1.4.6 is now latest. 

In the clear.

As you work to fix 2.x, please send updates to beta — we’ll all double confirm, assuming it works for you first :)

Thanks man. I do appreciate the time investment you make in these plugins!

**Comment by donavanbecker** [comment]
Try beta: v2.1.1

Also @tbaur, this isn't my full-time job, I do this as a hobby and when I have free time. If you choose to leave then that is that... I am trying the best I can. I have self thought myself to program with the help of some other great Homebridge plugin developers. If someone else has a fix for this I will never turn down a PR.

**Comment by sslupsky** [comment]
Is this the problem:

https://github.com/donavanbecker/homebridge-resideo/blob/b80a785097fc1d874845981929f4a752bcc60cf1/src/homebridge-ui/server.ts#L10

Seems to me this should import from settings.ts?

**Comment by donavanbecker** [comment]
no because typescript gets compiled to javascript.

@sslupsky, have you tired the latest beta?

**Comment by tbaur** [comment]
2.x including 2.1.1 -- they are all broken, do not work. 

Can not even try to relink, callback url is blank and uneditable. 

This is very trivial to test, are you testing the code before you are pushing out? Or just asking others?

Once more, please set 1.4.6 back to latest.
Please keep these beta until it actually works and confirmed, 2.0.1 should not be marked latest.

**Comment by donavanbecker** [comment]
@tbaur so you aren't even testing the beta?

**Comment by tbaur** [comment]
I just replied, 2.1.1 is broken, like all of the 2.x releases.

1.4.6 should remain set to latest.

**Comment by donavanbecker** [comment]
Your comments are really helpful. I am not having any issues with the beta. So I am releasing and closing this issue. If you can provide more helpful info then just saying it doesn't work or providing a PR, then I will merge the fix that you provide. Thanks.
