### ISSUE TITLE
Support Request: Unable to Sign In After Putting In Customer Key and Secret Key

### ISSUE THREAD

**Issue by CalvinDabrowski** [d0n4v4nb3ck3r/homebridge-honeywell-home#842]
### Describe Your Problem

Once I input customer key and secret key, and press link account, it shows my Homebridge IP and says This site can’t be reached (IP ADDRESS) Refused to Connect. I have disabled all firewall protection as well...

### Device & Model

Raspberry Pi

### Node.js Version

v20.10.0

### NPM Version

unsure

### Homebridge Version

unsure

### Homebridge Resideo Plugin Version

v2.1.5

### Operating System

raspbian

**Comment by clearfeather** [comment]
Downgrade to version 2.1.4 and try configuring again. You can upgrade to the latest version afterwards.

**Comment by donavanbecker** [comment]
@CalvinDabrowski I am guessing you are using HOOBs?
